name: Gas Report

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

env:
    FOUNDRY_PROFILE: ci

jobs:
    gas-report:
        name: Gas Report on Test Run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Run tests with gas report
              run: forge test --gas-report
